apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sdcs.streamsets.k8s.io
scope: Namespaced
spec:
  group: streamsets.k8s.io
  version: v1
  names:
    kind: SdcCustomResource
    plural: sdcs
    singular: sdc
